### ISSUE TITLE
Fix backfill script

### ISSUE THREAD

**Issue by brandendupont** [brandendupont-mcw/git_scrape_cook_jail#7]
Backfill script uses the current year to generate past reports. This incorrectly generates missed pdfs as the year changes. (i.e. December to January)

**Comment by brandendupont-mcw** [comment]
During the New Year, the pdf url also changed sporadically. This made a permanent fix infeasible.  Past data was backfilled manually as a one-time workaround. 

Since the 4th, the jail pdf upload seems to be working as expected.
